<?php
/* ==========================================================================
 *  AnimeX Leecher Bot  —  ربات لیچر انیمکس
 *  --------------------------------------------------------------------------
 *  ربات تلگرام برای استخراج لینک‌های دانلود از animex.click
 *  تک‌فایل • بدون نیاز به پروسس دائمی (وب‌هوک) • مناسب هاست اشتراکی
 *
 *  امکانات:
 *   - /start و خوش‌آمدگویی + پنل کاربری حرفه‌ای
 *   - فرستادن لینک animex → پوستر + کپشن (عنوان/سال/ژانر/امتیاز/وضعیت/توضیحات)
 *     + دکمه «مشاهده لینک‌های دانلود» → فایل مرتب (.txt) با همه لینک‌ها
 *   - محدودیت روزانه: ۵۰۰ درخواست در روز برای کاربر عادی (قابل تغییر)
 *   - کاربر VIP بدون محدودیت (تا تاریخ انقضا)
 *   - پنل ادمین حرفه‌ای (وب + دستورات داخل ربات)
 *       /setvip <id> <days>  /ban <id> [reason]  /unban <id>
 *       /addadmin <id>  /deladmin <id>  /stats  /broadcast <text>
 *       /userinfo <id>  /setlimit <n>  /claim <code>
 *
 *  نصب: فایل را در public_html آپلود کنید و آدرس زیر را در مرورگر باز کنید:
 *       https://your-domain/path/animex_bot.php?setup=BOT_TOKEN
 *  ==========================================================================
 */

declare(strict_types=1);
error_reporting(E_ALL & ~E_DEPRECATED & ~E_NOTICE & ~E_WARNING & ~E_NOTICE);
date_default_timezone_set('Asia/Tehran');

/* ============================ 0) مسیرها و کانفیگ ========================== */
define('AX_DIR', __DIR__);
define('AX_CONFIG', AX_DIR . '/config.php');
define('AX_DB', AX_DIR . '/animex.db');
define('AX_VER', '2.0');
define('AX_SRC', 'https://animex.click/');
define('AX_SUPPORT', '@Adlchannel');

function ax_cfg(?array $set = null): ?array {
    if ($set !== null) {
        // ذخیره به‌صورت کد PHP — با باز شدن از وب خروجی نمی‌دهد (توکن در امان می‌ماند)
        $php = "<?php\n// AUTO-GENERATED by AnimeX bot — do not edit\nreturn " . var_export($set, true) . ";\n";
        file_put_contents(AX_CONFIG, $php, LOCK_EX);
        return $set;
    }
    if (!is_file(AX_CONFIG)) return null;
    $c = @include AX_CONFIG;
    return is_array($c) ? $c : null;
}

/* ============================ 1) ذخیره‌سازی (SQLite) ====================== */
class AXStore {
    private SQLite3 $db;
    public function __construct() {
        $this->db = new SQLite3(AX_DB);
        $this->db->busyTimeout(5000);
        $this->db->exec('PRAGMA journal_mode=WAL');
        $this->db->exec('CREATE TABLE IF NOT EXISTS users(
            id INTEGER PRIMARY KEY, first_name TEXT, username TEXT,
            is_admin INTEGER DEFAULT 0, vip_until INTEGER DEFAULT 0,
            banned INTEGER DEFAULT 0, ban_reason TEXT,
            joined INTEGER, last_seen INTEGER, total_req INTEGER DEFAULT 0)');
        $this->db->exec('CREATE TABLE IF NOT EXISTS usage(
            user_id INTEGER, d TEXT, c INTEGER DEFAULT 0, PRIMARY KEY(user_id,d))');
        $this->db->exec('CREATE TABLE IF NOT EXISTS cache(
            hash TEXT PRIMARY KEY, url TEXT, data TEXT, created INTEGER)');
        $this->db->exec('CREATE TABLE IF NOT EXISTS logs(
            id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, action TEXT, url TEXT, ts INTEGER)');
    }
    public function ensure_user(int $id, string $first, string $uname): void {
        $q = $this->db->prepare('INSERT INTO users(id,first_name,username,joined,last_seen) VALUES(?,?,?,?,?)
            ON CONFLICT(id) DO UPDATE SET first_name=excluded.first_name, username=excluded.username, last_seen=excluded.last_seen');
        $now = time();
        $q->execute([$id, $first, $uname, $now, $now]);
    }
    public function get_user(int $id): ?array {
        $q = $this->db->prepare('SELECT * FROM users WHERE id=?');
        $r = $q->execute([$id]);
        $row = $r->fetchArray(SQLITE3_ASSOC);
        return $row ?: null;
    }
    public function set_admin(int $id, bool $v): void {
        $this->db->prepare('UPDATE users SET is_admin=? WHERE id=?')->execute([$v ? 1 : 0, $id]);
    }
    public function set_vip(int $id, int $days): void {
        $row = $this->get_user($id);
        $cur = $row ? (int)$row['vip_until'] : 0;
        $base = time() > $cur ? time() : $cur;
        $until = $base + $days * 86400;
        $this->db->prepare('UPDATE users SET vip_until=? WHERE id=?')->execute([$until, $id]);
    }
    public function ban(int $id, string $reason = ''): void {
        $this->db->prepare('UPDATE users SET banned=1, ban_reason=? WHERE id=?')->execute([$reason, $id]);
    }
    public function unban(int $id): void {
        $this->db->prepare('UPDATE users SET banned=0, ban_reason=NULL WHERE id=?')->execute([$id]);
    }
    public function usage_today(int $id): int {
        $r = $this->db->prepare('SELECT c FROM usage WHERE user_id=? AND d=?');
        $x = $r->execute([$id, date('Y-m-d')])->fetchArray(SQLITE3_ASSOC);
        return $x ? (int)$x['c'] : 0;
    }
    public function inc_usage(int $id): void {
        $this->db->prepare('INSERT INTO usage(user_id,d,c) VALUES(?,?,1)
            ON CONFLICT(user_id,d) DO UPDATE SET c=c+1')->execute([$id, date('Y-m-d')]);
        $this->db->prepare('UPDATE users SET total_req=total_req+1 WHERE id=?')->execute([$id]);
    }
    public function cache_get(string $hash): ?array {
        $r = $this->db->prepare('SELECT * FROM cache WHERE hash=?');
        $x = $r->execute([$hash])->fetchArray(SQLITE3_ASSOC);
        return $x ?: null;
    }
    public function cache_set(string $hash, string $url, string $data): void {
        $this->db->prepare('INSERT INTO cache(hash,url,data,created) VALUES(?,?,?,?)
            ON CONFLICT(hash) DO UPDATE SET url=excluded.url, data=excluded.data, created=excluded.created')
            ->execute([$hash, $url, $data, time()]);
    }
    public function log(int $uid, string $action, string $url = ''): void {
        $this->db->prepare('INSERT INTO logs(user_id,action,url,ts) VALUES(?,?,?,?)')->execute([$uid, $action, $url, time()]);
    }
    public function stats(): array {
        $q = fn(string $s) => (int)$this->db->querySingle($s);
        return [
            'users'    => $q('SELECT COUNT(*) FROM users'),
            'admins'   => $q('SELECT COUNT(*) FROM users WHERE is_admin=1'),
            'vip'      => $q('SELECT COUNT(*) FROM users WHERE vip_until>' . time()),
            'banned'   => $q('SELECT COUNT(*) FROM users WHERE banned=1'),
            'today'    => $q("SELECT COALESCE(SUM(c),0) FROM usage WHERE d='" . date('Y-m-d') . "'"),
            'total'    => $q('SELECT COALESCE(SUM(total_req),0) FROM users'),
            'cache'    => $q('SELECT COUNT(*) FROM cache'),
        ];
    }
    public function users_page(int $page = 0, int $per = 30): array {
        $off = $page * $per;
        $r = $this->db->query("SELECT * FROM users ORDER BY id DESC LIMIT $per OFFSET $off");
        $out = [];
        while ($row = $r->fetchArray(SQLITE3_ASSOC)) $out[] = $row;
        return $out;
    }
    public function all_ids(): array {
        $r = $this->db->query('SELECT id FROM users');
        $out = [];
        while ($row = $r->fetchArray(SQLITE3_ASSOC)) $out[] = (int)$row['id'];
        return $out;
    }
}
$AX_STORE = null;
function ax_store(): AXStore { global $AX_STORE; return $AX_STORE ?? ($AX_STORE = new AXStore()); }

/* ============================ 2) HTTP helper ============================== */
function ax_http(string $url, bool $bin = false, int $timeout = 25) {
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_MAXREDIRS      => 8,
        CURLOPT_TIMEOUT        => $timeout,
        CURLOPT_CONNECTTIMEOUT => 12,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_SSL_VERIFYHOST => false,
        CURLOPT_USERAGENT      => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
        CURLOPT_HTTPHEADER     => ['Accept-Language: fa,en;q=0.9', 'Accept: text/html,application/xhtml+xml,application/xml,*/*;q=0.8'],
        CURLOPT_ENCODING       => '',
    ]);
    $res = curl_exec($ch);
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    return $res;
}

/* ============================ 3) Telegram API ============================= */
function ax_tg(string $method, array $params = []) {
    $cfg = ax_cfg(); if (!$cfg) return null;
    $url = 'https://api.telegram.org/bot' . $cfg['bot_token'] . '/' . $method;
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST           => true,
        CURLOPT_POSTFIELDS     => $params,
        CURLOPT_TIMEOUT        => 50,
        CURLOPT_SSL_VERIFYPEER => false,
    ]);
    $res = curl_exec($ch); curl_close($ch);
    return json_decode($res, true);
}
function ax_tg_upload(string $method, array $fields, array $files) {
    $cfg = ax_cfg(); if (!$cfg) return null;
    $boundary = uniqid('ax', true);
    $eol = "\r\n"; $body = '';
    foreach ($fields as $k => $v) {
        if ($v === null || $v === '') continue;
        $body .= "--$boundary$eolContent-Disposition: form-data; name=\"$k\"$eol$eol$v$eol";
    }
    foreach ($files as $name => $path) {
        $body .= "--$boundary$eolContent-Disposition: form-data; name=\"$name\"; filename=\"" . basename($path) . "\"$eol";
        $body .= "Content-Type: application/octet-stream$eol$eol" . file_get_contents($path) . $eol;
    }
    $body .= "--$boundary--$eol";
    $ch = curl_init('https://api.telegram.org/bot' . $cfg['bot_token'] . '/' . $method);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true, CURLOPT_POST => true, CURLOPT_POSTFIELDS => $body,
        CURLOPT_HTTPHEADER => ['Content-Type: multipart/form-data; boundary=' . $boundary],
        CURLOPT_TIMEOUT => 90, CURLOPT_SSL_VERIFYPEER => false,
    ]);
    $res = curl_exec($ch); curl_close($ch);
    return json_decode($res, true);
}
function ax_send(int $chat, string $text, $markup = null, string $parse = 'HTML'): array {
    $p = ['chat_id' => $chat, 'text' => $text, 'parse_mode' => $parse];
    if ($markup) $p['reply_markup'] = is_string($markup) ? $markup : json_encode($markup, JSON_UNESCAPED_UNICODE);
    return ax_tg('sendMessage', $p);
}
function ax_answer(string $cbid, string $text = '', bool $alert = false): void {
    ax_tg('answerCallbackQuery', ['callback_query_id' => $cbid, 'text' => $text, 'show_alert' => $alert]);
}

/* ============================ 4) اسکرپر animex.click ====================== */
function ax_scrape(string $url): array {
    $url = trim($url);
    $html = ax_http($url);
    if (!$html) return ['ok' => false, 'error' => 'دریافت صفحه ناموفق بود (احتمالاً سایت در دسترس نیست).'];
    // ساخت DOM با charset درست (ترفند xml encoding برای UTF-8 در DOMDocument)
    $dom = new DOMDocument('1.0', 'UTF-8');
    libxml_use_internal_errors(true);
    $dom->loadHTML('<?xml encoding="UTF-8">' . $html);
    libxml_clear_errors();
    $xp = new DOMXPath($dom);

    // ---- متادیتا ----
    $meta = fn(string $sel) => ($n = $xp->query($sel)->item(0)) ? trim($n->nodeValue) : '';
    $ogimg = $meta('//meta[@property="og:image"]/@content') ?: $meta('//meta[@name="twitter:image"]/@content');
    $title = $meta('//meta[@property="og:title"]/@content') ?: trim(str_replace(['– انیمکس', '- انیمکس', '– انیمکس'], '', $meta('//title')));
    $desc  = $meta('//meta[@property="og:description"]/@content') ?: $meta('//meta[@name="description"]/@content');

    // استخراج فیلدها از متن صفحه
    $text = trim(preg_replace('/\s+/u', ' ', $dom->textContent));
    $field = function (string $label) use ($text): string {
        if (preg_match('#' . preg_quote($label, '#') . '\s*[:：]?\s*([^•|◆▪■\n]{1,120})#u', $text, $m)) return trim($m[1]);
        return '';
    };
    $year   = $field('سال انتشار') ?: $field('سال');
    $genres = $field('ژانر') ?: $field('انواع');
    $status = $field('وضعیت');
    $rate   = $field('امتیاز') ?: $field('مال');
    $country= $field('کشور');
    $age    = $field('رده سنی') ?: $field('محدوده سنی');

    // ---- لینک‌های دانلود ----
    $links = ax_extract_links($dom, $xp);

    return [
        'ok'   => true,
        'url'  => $url,
        'title'=> $title ?: parse_url($url, PHP_URL_PATH),
        'poster'=> $ogimg,
        'description'=> $desc,
        'meta' => ['year' => $year, 'genres' => $genres, 'status' => $status, 'rate' => $rate, 'country' => $country, 'age' => $age],
        'groups' => $links['groups'],
        'count' => $links['count'],
        'debug_context' => $links['debug'] ?? [],
    ];
}

function ax_is_dl_link(string $href): bool {
    $h = strtolower($href);
    if (strpos($h, 'hollowofthealley.space') !== false) return true;
    if (strpos($h, 'animexstream.fun') !== false) return true;
    if (strpos($h, '?dir=') !== false) return true;
    if (preg_match('#\.(mkv|mp4|avi|zip|rar|m4v|ts|mov|x265)(?:\?|#|$)#i', $h)) return true;
    return false;
}
function ax_text_of(DOMNode $n): string { return trim(preg_replace('/\s+/u', ' ', $n->textContent)); }

// جمع‌آوری متنِ قبل از یک گره (برای پیدا کردن کیفیت/فصل/زیرنویس)
function ax_preceding(DOMNode $node, int $max = 800): string {
    $out = ''; $n = $node; $depth = 0;
    while ($n && mb_strlen($out) < $max && $depth < 6) {
        $p = $n->previousSibling;
        while ($p && mb_strlen($out) < $max) {
            $t = ax_text_of($p);
            if ($t !== '') $out = $t . "\n" . $out;
            $p = $p->previousSibling;
        }
        $n = $n->parentNode; $depth++;
        if (!$n || strtoupper($n->nodeName) === 'BODY') break;
    }
    return $out;
}

function ax_extract_links(DOMDocument $dom, DOMXPath $xp): array {
    $anchors = $xp->query('//a[@href]');
    $items = [];
    $debug = [];
    foreach ($anchors as $a) {
        /** @var DOMElement $a */
        $href = $a->getAttribute('href');
        if (!ax_is_dl_link($href)) continue;
        $role = (strpos(ax_text_of($a), 'پخش') !== false || stripos(ax_text_of($a), 'online') !== false) ? 'stream' : 'download';

                $ctx = ax_preceding($a);
        $STOPS = '(?:دانلود با کیفیت|دانلود فصل|دانلود نسخه|دانلود زیرنویس|دانلود قسمت|پخش آنلاین)';
        // گروه (نزدیک‌ترین هدر): فصل / نسخه / زیرنویس / قسمت
        $group = '';
        if (preg_match_all('#(دانلود فصل|دانلود نسخه|دانلود زیرنویس|دانلود قسمت)\s*((?:(?!' . $STOPS . ')[^\n])*)#u', $ctx, $mg, PREG_SET_ORDER)) {
            $lg = end($mg); $group = trim($lg[1] . ($lg[2] !== '' ? ' ' . $lg[2] : ''));
        }
        $isSub = ($group !== '' && mb_strpos($group, 'دانلود زیرنویس') === 0);
        // کیفیت (نزدیک‌ترین)
        $quality = '';
        if (!$isSub && preg_match_all('#دانلود با کیفیت\s*((?:(?!' . $STOPS . ')[^\n])*)#u', $ctx, $mq, PREG_SET_ORDER)) {
            $quality = trim(end($mq)[1]);
        }
        // نوع زیرنویس (نزدیک‌ترین)
        $sub = '';
        if (!$isSub && preg_match_all('#(زیرنویس چسبیده|سافت\s*ساب|دوبله فارسی|فاقد زیرنویس)\s*((?:(?!' . $STOPS . ')[^\n])*)#u', $ctx, $ms2, PREG_SET_ORDER)) {
            $ls = end($ms2); $sub = trim($ls[1] . ($ls[2] !== '' ? ' ' . $ls[2] : ''));
        }
        // سایز
        $size = '';
        if (preg_match('#(\d+(?:\.\d+)?\s*(?:GB|MB|TB))#ui', $ctx, $mz)) $size = strtoupper(preg_replace('/\s+/', '', $mz[1]));

        if ($isSub) {
            $quality = 'فایل زیرنویس';
        } else {
            if ($group !== '' && $sub !== '' && mb_strpos($group, $sub) === false) $group = $group . ' • ' . $sub;
            if ($quality === '') $quality = ($role === 'stream') ? 'پخش آنلاین' : 'لینک دانلود';
        }
        if ($group === '') $group = 'دانلود';

        $items[] = compact('role', 'href', 'group', 'quality', 'size', 'sub');
        if (count($debug) < 8) $debug[] = ['group' => $group, 'quality' => $quality, 'size' => $size, 'href' => $href];
    }
    // ساخت درخت گروه → کیفیت → لینک‌ها
    $tree = [];
    foreach ($items as $it) {
        $g = $it['group']; $q = $it['quality'];
        $tree[$g][$q] = $tree[$g][$q] ?? ['size' => $it['size'], 'download' => null, 'stream' => null];
        if ($it['role'] === 'download' && !$tree[$g][$q]['download']) $tree[$g][$q]['download'] = $it['href'];
        if ($it['role'] === 'stream' && !$tree[$g][$q]['stream']) $tree[$g][$q]['stream'] = $it['href'];
        if ($it['size'] && !$tree[$g][$q]['size']) $tree[$g][$q]['size'] = $it['size'];
    }
    return ['groups' => $tree, 'count' => count($items), 'debug' => $debug];
}

// بسط پوشه‌های دانلود (?dir=) به لینک‌های تک‌قسمت (best-effort)
function ax_expand_dir(string $url): array {
    $html = ax_http($url, false, 12);
    if (!$html) return [];
    if (preg_match('#application/json#i', substr($html, 0, 200)) && $json = json_decode($html, true)) {
        $out = [];
        foreach (($json['files'] ?? $json['items'] ?? $json) as $f) {
            if (is_array($f) && isset($f['name'], $f['url'])) $out[] = ['name' => $f['name'], 'url' => $f['url']];
        }
        return array_slice($out, 0, 200);
    }
    $d = new DOMDocument('1.0', 'UTF-8');
    libxml_use_internal_errors(true);
    $d->loadHTML('<?xml encoding="UTF-8">' . $html);
    libxml_clear_errors();
    $xp = new DOMXPath($d);
    $out = [];
    foreach ($xp->query('//a[@href]') as $a) {
        $h = $a->getAttribute('href');
        $t = trim($a->textContent);
        if ($t === '' || in_array($t, ['..', '.', 'Parent Directory'], true)) continue;
        if (preg_match('#\.(mkv|mp4|m4v|avi|zip|ts|mov)(?:\?|$)#i', $h)) {
            $out[] = ['name' => $t, 'url' => strpos($h, 'http') === 0 ? $h : rtrim($url, '/') . '/' . ltrim($h, '/')];
        }
    }
    return array_slice($out, 0, 200);
}

/* ============================ 5) پیام‌سازی ================================ */
function ax_caption(array $s): string {
    $m = $s['meta'];
    $lines = [];
    $lines[] = '🎬 <b>' . htmlspecialchars($s['title']) . '</b>';
    if ($m['year'])    $lines[] = "📅 سال انتشار: {$m['year']}";
    if ($m['genres'])  $lines[] = "🎭 ژانر: {$m['genres']}";
    if ($m['rate'])    $lines[] = "⭐ امتیاز: {$m['rate']}";
    if ($m['status'])  $lines[] = "📌 وضعیت: {$m['status']}";
    if ($m['country']) $lines[] = "🌍 کشور: {$m['country']}";
    if ($m['age'])     $lines[] = "🔞 رده سنی: {$m['age']}";
    $lines[] = "🔗 تعداد لینک استخراج‌شده: <b>{$s['count']}</b>";
    $desc = trim($s['description']);
    if ($desc !== '') {
        $remain = 950 - strlen(implode("\n", $lines));
        if ($remain > 40) {
            $lines[] = '';
            $lines[] = '📝 ' . mb_substr($desc, 0, max(60, $remain));
        }
    }
    return implode("\n", $lines);
}

function ax_build_txt(array $s): string {
    $m = $s['meta'];
    $t = [];
    $bar = str_repeat('═', 48);
    $t[] = $bar;
    $t[] = '  ' . $s['title'];
    $t[] = $bar;
    if ($m['year'])    $t[] = "سال انتشار : " . $m['year'];
    if ($m['genres'])  $t[] = "ژانر : " . $m['genres'];
    if ($m['rate'])    $t[] = "امتیاز : " . $m['rate'];
    if ($m['status'])  $t[] = "وضعیت : " . $m['status'];
    if ($m['country']) $t[] = "کشور : " . $m['country'];
    if ($m['age'])     $t[] = "رده سنی : " . $m['age'];
    $t[] = "منبع : " . $s['url'];
    $t[] = '';
    foreach ($s['groups'] as $group => $quals) {
        $t[] = str_repeat('─', 48);
        $t[] = "📁 " . $group;
        foreach ($quals as $q => $info) {
            $sz = $info['size'] ? "  [{$info['size']}]" : '';
            $t[] = "    ▪ کیفیت {$q}{$sz}";
            if ($info['download']) {
                $t[] = "        ▶ دانلود : " . $info['download'];
                // اگر پوشه بود، تک‌قسمت‌ها را هم بیاور
                if (strpos($info['download'], '?dir=') !== false) {
                    $eps = ax_expand_dir($info['download']);
                    if ($eps) {
                        foreach ($eps as $ep) $t[] = "            • {$ep['name']} : {$ep['url']}";
                    }
                }
            }
            if ($info['stream']) $t[] = "        ▶ پخش آنلاین : " . $info['stream'];
        }
    }
    $t[] = '';
    $t[] = str_repeat('─', 48);
    $t[] = "✅ برای دانلود، لینک‌ها را در مرورگر یا دانلودمنیجر کپی کنید.";
    $t[] = "🤖 استخراج خودکار توسط ربات لیچر انیمکس";
    return implode("\n", $t);
}

function ax_safe_name(string $title): string {
    $t = trim(preg_replace('/[^\p{L}\p{N}\-_ ]/u', '', $title));
    return mb_substr($t !== '' ? $t : 'animex', 0, 40);
}

/* ============================ 6) پردازش درخواست کاربر ==================== */
function ax_process_url(int $chat, int $uid, string $url): void {
    $u = ax_store()->get_user($uid);
    if ($u && (int)$u['banned'] === 1) { ax_send($chat, "🚫 شما مسدود شده‌اید.\nدلیل: " . ($u['ban_reason'] ?: '—')); return; }
    $cfg = ax_cfg();
    $limit = (int)($cfg['daily_limit'] ?? 500);
    $isVip = $u && (int)$u['vip_until'] > time();
    if (!$isVip) {
        $used = ax_store()->usage_today($uid);
        if ($used >= $limit) {
            $reset = strtotime('tomorrow 00:00') - time();
            $h = floor($reset / 3600);
            ax_send($chat, "⛔ سقف روزانه شما ({<b>$limit</b>} درخواست) پر شده است.\nبعداً تلاش کنید (حدود {$h} ساعت تا ریست).\n\n💎 برای استفاده نامحدود، اشتراک VIP بگیرید.");
            return;
        }
    }
    if (!preg_match('#^https?://#i', $url)) $url = 'https://' . $url;

    ax_send($chat, "🔍 در حال استخراج اطلاعات از سایت ...");
    $hash = hash('sha1', $url);
    $cached = ax_store()->cache_get($hash);
    $s = $cached ? json_decode($cached['data'], true) : null;
    if (!$s) {
        $s = ax_scrape($url);
        if (!empty($s['ok'])) ax_store()->cache_set($hash, $url, json_encode($s, JSON_UNESCAPED_UNICODE));
    }
    if (empty($s['ok'])) { ax_send($chat, "❌ " . ($s['error'] ?? 'خطا در استخراج. لینک را بررسی کنید.')); return; }

    ax_store()->inc_usage($uid);
    ax_store()->log($uid, 'scrape', $url);

    $caption = ax_caption($s);
    $markup = ['inline_keyboard' => [[['text' => '🎬 مشاهده لینک‌های دانلود', 'callback_data' => 'dl|' . $hash]]]];
    if (!empty($s['poster'])) {
        $r = ax_tg('sendPhoto', [
            'chat_id' => $chat, 'photo' => $s['poster'], 'caption' => $caption,
            'parse_mode' => 'HTML', 'reply_markup' => json_encode($markup, JSON_UNESCAPED_UNICODE)]);
        if (empty($r['ok'])) { // fallback: دانلود پوستر و آپلود
            $bin = ax_http($s['poster'], true, 15);
            if ($bin) {
                $tmp = tempnam(sys_get_temp_dir(), 'px') . '.jpg';
                file_put_contents($tmp, $bin);
                ax_tg_upload('sendPhoto', [
                    'chat_id' => $chat, 'caption' => $caption, 'parse_mode' => 'HTML',
                    'reply_markup' => json_encode($markup, JSON_UNESCAPED_UNICODE)], ['photo' => $tmp]);
                @unlink($tmp);
            } else {
                ax_send($chat, $caption, $markup);
            }
        }
    } else {
        ax_send($chat, $caption, $markup);
    }
}

function ax_send_links_file(int $chat, int $uid, string $hash): void {
    $c = ax_store()->cache_get($hash);
    $s = $c ? json_decode($c['data'], true) : null;
    if (!$s) { ax_send($chat, "⏳ اطلاعات منقضی شده. لطفاً لینک را دوباره بفرستید."); return; }
    $txt = ax_build_txt($s);
    $tmp = tempnam(sys_get_temp_dir(), 'ax') . '.txt';
    file_put_contents($tmp, "\xEF\xBB\xBF" . $txt); // BOM برای نمایش درست فارسی در ویندوز
    ax_tg_upload('sendDocument', [
        'chat_id' => $chat,
        'caption' => "📦 همه لینک‌های دانلود «" . $s['title'] . "»",
    ], ['document' => $tmp]);
    @unlink($tmp);
}

/* ============================ 7) پنل کاربری (داخل ربات) ================== */
function ax_user_panel(int $chat, int $uid): void {
    $u = ax_store()->get_user($uid);
    $cfg = ax_cfg();
    $limit = (int)($cfg['daily_limit'] ?? 500);
    $isVip = $u && (int)$u['vip_until'] > time();
    $used = ax_store()->usage_today($uid);
    $vipTxt = $isVip ? ("💎 VIP فعال\nexpires: " . jdate((int)$u['vip_until'])) : '🆓 کاربر عادی';
    $rem = $isVip ? 'نامحدود' : max(0, $limit - $used);
    $txt = "👤 <b>پنل کاربری شما</b>\n\n"
         . "🆔 شناسه: <code>$uid</code>\n"
         . "$vipTxt\n"
         . "📊 درخواست امروز: <b>$used</b> / " . ($isVip ? '∞' : $limit) . "\n"
         . "♻️ باقی‌مانده امروز: <b>$rem</b>\n"
         . "📈 کل درخواست‌ها: <b>" . ((int)($u['total_req'] ?? 0)) . "</b>";
    $kbd = ['inline_keyboard' => [
        [['text' => '🔄 بروزرسانی', 'callback_data' => 'upanel']],
        [['text' => '📢 کانال', 'url' => 'https://t.me/Adlchannel'], ['text' => '📖 راهنما', 'callback_data' => 'help']],
    ]];
    ax_send($chat, $txt, $kbd);
}
// تاریخ شمسی ساده
function jdate(int $ts): string {
    $g = date('Y-m-d', $ts);
    require_once AX_DIR . '/jdatetime.php';
    return (function_exists('jdate_fmt')) ? jdate_fmt($g) : $g;
}

/* ============================ 8) دستورات ادمین =========================== */
function ax_is_admin(int $uid): bool {
    $u = ax_store()->get_user($uid);
    return $u && (int)$u['is_admin'] === 1;
}
function ax_admin_dispatch(int $chat, int $uid, string $text): bool {
    if (!ax_is_admin($uid)) return false;
    $parts = preg_split('/\s+/', trim($text));
    $cmd = strtolower(ltrim($parts[0] ?? '', '/'));
    switch ($cmd) {
        case 'setvip':
            $id = (int)($parts[1] ?? 0); $days = (int)($parts[2] ?? 0);
            if ($id <= 0 || $days <= 0) { ax_send($chat, "❗ کاربرد: /setvip <id> <days>"); break; }
            ax_store()->ensure_user($id, '-', '-');
            ax_store()->set_vip($id, $days);
            ax_send($chat, "✅ VIP به <code>$id</code> برای <b>$days</b> روز اعمال شد."); break;
        case 'ban':
            $id = (int)($parts[1] ?? 0);
            if ($id <= 0) { ax_send($chat, "❗ کاربرد: /ban <id> [reason]"); break; }
            $reason = trim(implode(' ', array_slice($parts, 2)));
            ax_store()->ensure_user($id, '-', '-');
            ax_store()->ban($id, $reason);
            ax_send($chat, "🚫 کاربر <code>$id</code> مسدود شد."); break;
        case 'unban':
            $id = (int)($parts[1] ?? 0);
            if ($id <= 0) { ax_send($chat, "❗ کاربرد: /unban <id>"); break; }
            ax_store()->unban($id); ax_send($chat, "✅ کاربر <code>$id</code> آزاد شد."); break;
        case 'addadmin':
            $id = (int)($parts[1] ?? 0);
            if ($id <= 0) { ax_send($chat, "❗ کاربرد: /addadmin <id>"); break; }
            ax_store()->ensure_user($id, '-', '-');
            ax_store()->set_admin($id, true); ax_send($chat, "✅ <code>$id</code> ادمین شد."); break;
        case 'deladmin':
            $id = (int)($parts[1] ?? 0);
            ax_store()->set_admin($id, false); ax_send($chat, "✅ <code>$id</code> از ادمینی برداشته شد."); break;
        case 'userinfo':
            $id = (int)($parts[1] ?? 0); $u = ax_store()->get_user($id);
            if (!$u) { ax_send($chat, "❌ کاربر یافت نشد."); break; }
            ax_send($chat, "👤 اطلاعات کاربر <code>$id</code>:\n" . json_encode($u, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)); break;
        case 'setlimit':
            $n = (int)($parts[1] ?? -1); if ($n < 0) { ax_send($chat, "❗ کاربرد: /setlimit <n>"); break; }
            $cfg = ax_cfg(); $cfg['daily_limit'] = $n; ax_cfg($cfg);
            ax_send($chat, "✅ سقف روزانه به <b>$n</b> تغییر کرد."); break;
        case 'stats':
            ax_send($chat, "📊 <b>آمار ربات</b>\n" . json_encode(ax_store()->stats(), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)); break;
        case 'broadcast':
            $msg = trim(substr($text, strpos($text, ' ')));
            if ($msg === '') { ax_send($chat, "❗ کاربرد: /broadcast <text>"); break; }
            $ids = ax_store()->all_ids(); $ok = 0;
            foreach ($ids as $to) { $r = ax_send($to, $msg); if (!empty($r['ok'])) $ok++; }
            ax_send($chat, "✅ پیام به $ok کاربر ارسال شد."); break;
        default: return false;
    }
    return true;
}

/* ============================ 9) روتر اصلی آپدیت ========================= */
function ax_handle(): void {
    $raw = file_get_contents('php://input');
    $u = json_decode($raw, true);
    if (!is_array($u)) return;

    if (isset($u['callback_query'])) {
        $cq = $u['callback_query'];
        $uid = (int)$cq['from']['id'];
        $chat = (int)$cq['message']['chat']['id'];
        $data = $cq['data'];
        ax_store()->ensure_user($uid, $cq['from']['first_name'] ?? '', $cq['from']['username'] ?? '');
        if (strpos($data, 'dl|') === 0) {
            ax_answer($cq['id'], '⏳ در حال ساخت فایل ...');
            ax_send_links_file($chat, $uid, substr($data, 3));
        } elseif ($data === 'upanel') { ax_user_panel($chat, $uid); ax_answer($cq['id']); }
        elseif ($data === 'help') { ax_answer($cq['id']); ax_help($chat); }
        return;
    }

    $msg = $u['message'] ?? null;
    if (!$msg) return;
    $uid = (int)$msg['from']['id'];
    $chat = (int)$msg['chat']['id'];
    $text = trim($msg['text'] ?? '');
    ax_store()->ensure_user($uid, $msg['from']['first_name'] ?? '', $msg['from']['username'] ?? '');

    // claim ownership
    if (strpos($text, '/claim') === 0) {
        $cfg = ax_cfg(); $code = trim(substr($text, 6));
        if ($code !== '' && hash_equals((string)$cfg['owner_code'], $code)) {
            ax_store()->set_admin($uid, true);
            $cfg['owner_id'] = $uid; ax_cfg($cfg);
            ax_send($chat, "🎉 شما مالک/ادمین ارشد ربات شدید!\nاکنون می‌توانید از دستورات ادمین استفاده کنید.\nکد شناسه شما: <code>$uid</code>");
        } else ax_send($chat, "❌ کد نامعتبر است.");
        return;
    }

    if (strpos($text, '/') === 0) {
        $cmd = strtolower(explode(' ', $text)[0]);
        if (ax_admin_dispatch($chat, $uid, $text)) return;
        switch ($cmd) {
            case '/start':
                $u0 = ax_store()->get_user($uid);
                ax_send($chat,
                    "👋 سلام " . htmlspecialchars($msg['from']['first_name'] ?? '') . "!\n\n"
                    . "🎬 <b>ربات لیچر انیمکس</b>\n"
                    . "کافیست <b>لینک صفحه انیمه/فیلم/سریال</b> از سایت animex.click را بفرستید تا:\n"
                    . "  • پوستر + اطلاعات (سال، ژانر، امتیاز، توضیحات) دریافت کنید\n"
                    . "  • با زدن دکمه «مشاهده لینک‌های دانلود»، همه لینک‌ها را به‌صورت <b>مرتب و فایل‌شده</b> تحویل بگیرید\n\n"
                    . "📊 سقف روزانه: <b>" . (ax_cfg()['daily_limit'] ?? 500) . "</b> درخواست",
                    ['inline_keyboard' => [[['text' => '👤 پنل کاربری', 'callback_data' => 'upanel']]]]);
                break;
            case '/panel': case '/myaccount': ax_user_panel($chat, $uid); break;
            case '/id': ax_send($chat, "🆔 شناسه شما: <code>$uid</code>"); break;
            case '/help': case '/start_help': ax_help($chat); break;
            default:
                ax_send($chat, "❓ دستور نامشخص. /help را ببینید یا یک لینک animex بفرستید.");
        }
        return;
    }

    if (preg_match('#https?://[^\s]+#i', $text, $mm)) { ax_process_url($chat, $uid, $mm[0]); return; }
    ax_send($chat, "🔗 لطفاً یک <b>لینک معتبر</b> از animex.click بفرستید.\nمثال: <code>https://animex.click/anime/...</code>");
}
function ax_help(int $chat): void {
    ax_send($chat,
        "📖 <b>راهنمای ربات</b>\n\n"
        . "1) لینک صفحه انیمه/فیلم را از animex.click کپی و بفرستید.\n"
        . "2) ربات پوستر + اطلاعات را می‌فرستد.\n"
        . "3) دکمه «🎬 مشاهده لینک‌های دانلود» را بزنید تا فایل لینک‌ها برسد.\n\n"
        . "دستورها:\n/start /panel /id /help");
}

/* ============================ 10) وب — نصب/پنل/تست ====================== */
function ax_self_url(): string {
    $https = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') || ($_SERVER['SERVER_PORT'] ?? '') == 443
        || (strtolower($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https');
    $scheme = $https ? 'https' : 'http';
    return $scheme . '://' . ($_SERVER['HTTP_HOST'] ?? 'localhost') . ($_SERVER['SCRIPT_NAME'] ?? '/animex_bot.php');
}
function ax_page(string $title, string $body): void {
    header('Content-Type: text/html; charset=utf-8');
    echo "<!doctype html><html lang='fa' dir='rtl'><head><meta charset='utf-8'>"
       . "<meta name='viewport' content='width=device-width,initial-scale=1'>"
       . "<title>$title</title><style>"
       . "body{font-family:Tahoma,sans-serif;background:#0f1424;color:#e6e9f2;margin:0;padding:24px;line-height:1.8}"
       . ".box{max-width:760px;margin:0 auto;background:#171c30;border:1px solid #2a3358;border-radius:16px;padding:24px}"
       . "h1{color:#7aa2ff;margin-top:0} code,pre{background:#0b1020;border:1px solid #2a3358;border-radius:8px;padding:2px 6px;direction:ltr;display:inline-block}"
       . "pre{padding:12px;overflow:auto} a{color:#7aa2ff} .ok{color:#3ddc84} .warn{color:#ffb454} .btn{display:inline-block;background:#3b6dff;color:#fff;padding:10px 18px;border-radius:10px;text-decoration:none}"
       . "</style></head><body><div class='box'>$body</div></body></html>";
}
function ax_setup(string $token, array $q): void {
    $token = preg_replace('/[^0-9A-Za-z:_\-]/', '', $token);
    if ($token === '') { ax_page('خطا', '<h1>❌ توکن خالی است</h1>'); return; }
    // اعتبارسنجی توکن
    $chk = json_decode((string)ax_http('https://api.telegram.org/bot' . $token . '/getMe'), true);
    if (empty($chk['ok'])) { ax_page('خطا', '<h1>❌ توکن نامعتبر است</h1><pre>' . htmlspecialchars($chk['description'] ?? 'getMe failed') . '</pre>'); return; }
    $base = ax_self_url();
    $webhookSecret = bin2hex(random_bytes(16));
    $panelSecret = bin2hex(random_bytes(16));
    $ownerCode = strtoupper(substr(bin2hex(random_bytes(4)), 0, 8));
    $cfg = [
        'bot_token' => $token,
        'bot_username' => $chk['result']['username'] ?? '',
        'webhook_secret' => $webhookSecret,
        'panel_secret' => $panelSecret,
        'owner_code' => $ownerCode,
        'owner_id' => null,
        'daily_limit' => isset($q['limit']) ? (int)$q['limit'] : 500,
        'vip_unlimited' => true,
        'cache_ttl' => 86400,
        'ver' => AX_VER,
    ];
    ax_cfg($cfg);
    // init db
    try { ax_store(); } catch (Throwable $e) { ax_page('خطا', '<h1>❌ ساخت دیتابیس ناموفق بود</h1><pre>' . htmlspecialchars($e->getMessage()) . '</pre><p>مطمئن شوید پوشنده قابل‌نوشتن است.</p>'); return; }
    // set webhook
    $hookUrl = $base . '?hook=' . $webhookSecret;
    $wh = json_decode((string)ax_http('https://api.telegram.org/bot' . $token . '/setWebhook?url=' . urlencode($hookUrl) . '&drop_pending_updates=true&max_connections=40'), true);
    $hookOk = !empty($wh['ok']);
    $panelUrl = $base . '?panel=' . $panelSecret;
    $bot = '@' . ($chk['result']['username'] ?? 'bot');
    $hookCls = $hookOk ? 'ok' : 'warn';
    $hookTxt = $hookOk ? 'فعال ✅' : '⚠️ تنظیم نشد (بعداً تلاش کنید)';
    $body = "<h1>✅ ربات با موفقیت نصب شد</h1>"
         . "<p>🤖 ربات: <b>$bot</b></p>"
         . "<p class='$hookCls'>وب‌هوک: $hookTxt</p>"
         . "<hr><h3>🔑 مالکیت ربات را بگیرید</h3>"
         . "<p>این پیام را به ربات <b>$bot</b> بفرستید تا ادمین ارشد شوید:</p>"
         . "<pre>/claim $ownerCode</pre>"
         . "<hr><h3>🖥️ پنل مدیریت وب</h3>"
         . "<p><a class='btn' href='$panelUrl' target='_blank'>ورود به پنل ادمین</a></p>"
         . "<code>$panelUrl</code>"
         . "<hr><h3>🧪 تست استخراج</h3>"
         . "<p>برای تست، آدرس زیر را با لینک نمونه باز کنید:</p>"
         . "<code>" . htmlspecialchars($base) . "?test=LINK_ANIMEX</code>"
         . "<p class='warn'>⚠️ این آدرس‌ها را محرمانه نگه دارید.</p>";
    ax_page('✅ نصب کامل شد', $body);
}
function ax_unhook(string $token): void {
    $token = preg_replace('/[^0-9A-Za-z:_\-]/', '', $token);
    $r = json_decode((string)ax_http('https://api.telegram.org/bot' . $token . '/deleteWebhook'), true);
    ax_page('Webhook', '<h1>وب‌هوک حذف شد</h1><pre>' . htmlspecialchars(json_encode($r, JSON_PRETTY_PRINT)) . '</pre>');
}
function ax_panel(string $secret, array $q): void {
    $cfg = ax_cfg(); if (!$cfg || !hash_equals((string)$cfg['panel_secret'], (string)$secret)) { http_response_code(403); ax_page('403', '<h1>403 — دسترسی غیرمجاز</h1>'); return; }
    $st = ax_store();
    // اکشن‌ها
    if (isset($q['act'], $q['id'])) {
        $id = (int)$q['id'];
        if ($q['act'] === 'ban') $st->ban($id, 'panel');
        if ($q['act'] === 'unban') $st->unban($id);
        if ($q['act'] === 'vip') $st->set_vip($id, (int)($q['days'] ?? 30));
        if ($q['act'] === 'admin') $st->set_admin($id, true);
        if ($q['act'] === 'unadmin') $st->set_admin($id, false);
        header('Location: ' . ax_self_url() . '?panel=' . $secret); return;
    }
    $s = $st->stats();
    $rows = '';
    foreach ($st->users_page((int)($q['p'] ?? 0)) as $u) {
        $vip = (int)$u['vip_until'] > time() ? '💎' : '';
        $adm = (int)$u['is_admin'] === 1 ? '🛡️' : '';
        $ban = (int)$u['banned'] === 1 ? '🚫' : '';
        $btns = "<a href='?panel=$secret&act=" . ((int)$u['banned'] === 1 ? "unban" : "ban") . "&id={$u['id']}'>" . ((int)$u['banned'] === 1 ? 'آزاد' : 'بن') . "</a> · "
              . "<a href='?panel=$secret&act=vip&id={$u['id']}&days=30'>VIP30</a> · "
              . "<a href='?panel=$secret&act=" . ((int)$u['is_admin'] === 1 ? 'unadmin' : 'admin') . "&id={$u['id']}'>" . ((int)$u['is_admin'] === 1 ? 'حذف ادمین' : 'ادمین') . "</a>";
        $rows .= "<tr><td>{$u['id']}</td><td>" . htmlspecialchars((string)$u['first_name']) . "</td><td>$vip$adm$ban</td><td>{$u['total_req']}</td><td style='direction:ltr;text-align:right'>$btns</td></tr>";
    }
    $bot = '@' . ($cfg['bot_username'] ?? '');
    ax_page('پنل مدیریت', "
    <h1>🖥️ پنل مدیریت ربات $bot</h1>
    <p>👥 کاربران: <b>{$s['users']}</b> | 🛡️ ادمین: <b>{$s['admins']}</b> | 💎 VIP: <b>{$s['vip']}</b> | 🚫 بن: <b>{$s['banned']}</b></p>
    <p>📊 درخواست امروز: <b>{$s['today']}</b> | کل: <b>{$s['total']}</b> | کش: <b>{$s['cache']}</b></p>
    <p>⚙️ سقف روزانه: <b>" . ($cfg['daily_limit'] ?? 500) . "</b></p>
    <hr><h3>کاربران (اخرین)</h3>
    <div style='overflow:auto'><table border='1' cellpadding='6' style='border-collapse:collapse;width:100%'>
    <tr><th>ID</th><th>نام</th><th>وضعیت</th><th>کل درخواست</th><th>عملیات</th></tr>$rows</table></div>");
}

/* ============================ 11) دیسپچ نهایی =========================== */
if (isset($_GET['setup'])) { ax_setup((string)$_GET['setup'], $_GET); exit; }
if (isset($_GET['unhook'])) { ax_unhook((string)$_GET['unhook']); exit; }

$cfg = ax_cfg();
if (!$cfg) {
    $base = ax_self_url();
    ax_page('نصب ربات', "<h1>🤖 ربات لیچر انیمکس — نصب</h1>
    <p>برای راه‌اندازی، توکن ربات خود را از <b>@BotFather</b> بردارید و آدرس زیر را در مرورگر باز کنید:</p>
    <pre>" . htmlspecialchars($base) . "?setup=BOT_TOKEN</pre>
    <p>مثال:</p>
    <pre>" . htmlspecialchars($base) . "?setup=123456:ABC-DEF...</pre>
    <p class='warn'>⚠️ نیازمندی‌ها: PHP 7.4+ با ext-curl، ext-sqlite3، ext-mbstring، ext-dom (در اکثر هاست‌ها فعال است).</p>");
    exit;
}
if (isset($_GET['test'])) {
    $tu = urldecode((string)$_GET['test']);
    $host = strtolower((string)parse_url($tu, PHP_URL_HOST));
    header('Content-Type: application/json; charset=utf-8');
    if (strpos($host, 'animex') === false) {
        echo json_encode(['error' => 'فقط لینک‌های animex.click مجاز است.'], JSON_UNESCAPED_UNICODE);
    } else {
        echo json_encode(ax_scrape($tu), JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
    }
    exit;
}
if (isset($_GET['panel'])) { ax_panel((string)$_GET['panel'], $_GET); exit; }
if (isset($_GET['hook']) && hash_equals((string)$cfg['webhook_secret'], (string)$_GET['hook'])) {
    try { ax_handle(); } catch (Throwable $e) { ax_store()->log(0, 'error', $e->getMessage()); }
    header('Content-Type: application/json'); echo '{"ok":true}';
    exit;
}
$uname = $cfg['bot_username'] ?? 'bot';
ax_page('ربات فعال ✅', "<h1>✅ ربات لیچر انیمکس فعال است</h1><p>ربات @$uname روی وب‌هوک قرار دارد.</p><p>برای تست استخراج: <code>?test=LINK</code></p>");
